language: crystal
script:
  - crystal tool format --check
  - crystal spec
  - crystal docs
before_deploy:
  - cp -R images doc/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc
  on:
    branch: master
